/** Libellés français — éditeur CV (mode Digimytch Talent Hub) */
export const RESUME_LABELS_FR = {
  identity: "Identité",
  experiences: "Expériences",
  projects: "Projets",
  education: "Formation",
  skills: "Compétences",
  layout: "Mise en page",
  scoreCV: "Score CV",
  coverLetter: "Lettre",
  baseResume: "CV de base",
  tailoredResume: "CV sur mesure",
  fillFromProfile: "Remplir depuis le profil",
  importFromProfile: "Importer depuis le profil",
  addExperience: "Ajouter une expérience",
  addProject: "Ajouter un projet",
  addEducation: "Ajouter une formation",
  addSkill: "Ajouter une compétence",
  addPoint: "Ajouter un point",
  addTechnology: "Ajouter une technologie",
  writeWithAI: "Rédiger avec l'IA",
  writePointsWithAI: "Générer des points avec l'IA",
  clearChatHistory: "Effacer l'historique",
  createCoverLetter: "Créer ma lettre de motivation",
  createTailoredResume: "Créer un CV sur mesure",
  newBaseResume: "Nouveau CV de base",
  newTailoredResume: "Nouveau CV sur mesure",
  savedStyles: "Styles sauvegardés",
  defaultLayout: "Mise en page standard",
  compactLayout: "Mise en page compacte",
  import: "Importer",
  download: "Télécharger",
  save: "Enregistrer",
  unsavedChanges: "Modifications non enregistrées",
  saveChanges: "Enregistrer les modifications",
  leave: "Quitter",
  cancel: "Annuler",
  projectName: "Nom du projet",
  liveUrl: "URL en ligne",
  githubUrl: "URL GitHub",
  date: "Date",
  keyFeatures: "Réalisations clés",
  technologiesUsed: "Technologies utilisées",
  selectContentToInclude: "Sélectionner le contenu à inclure",
  establishment: "Établissement",
  city: "Ville",
  country: "Pays",
  degree: "Diplôme",
  fieldOfStudy: "Domaine d'études",
  gpa: "Mention (optionnel)",
  achievementsActivities: "Distinctions et activités",
  fontSize: "Taille de police",
  lineHeight: "Interligne",
  verticalMargins: "Marges verticales",
  horizontalMargins: "Marges horizontales",
  spaceAboveSection: "Espace avant la section",
  spaceBelowSection: "Espace après la section",
  spaceBetweenItems: "Espace entre les éléments",
  nameSize: "Taille du nom",
  spaceBelowName: "Espace sous le nom",
  aiSuggestion: "Suggestion IA",
  accept: "Accepter",
  reject: "Rejeter",
  askAboutResume: "Posez une question sur votre CV…",
  startWritingCoverLetter: "Commencez à rédiger votre lettre…",
  createCVTailoredFirst:
    "Créez d'abord un CV sur mesure lié à une offre pour générer une lettre adaptée.",
  successSaved: "CV enregistré avec succès",
  errorApiKey: "Clé API manquante — configurez-la dans Paramètres",
  errorGeneric: "Une erreur est survenue",
  noBaseResumes: "Aucun CV de base",
  createBaseResumeFirst: "Créez d'abord un CV de base.",
  placeholderDate: 'ex. Jan 2023 - Présent ou 2020 - 2022',
  emptySection: "vide",
  copyBaseResume: "Copier le CV de base",
  leaveWithoutSaving: "Quitter sans enregistrer",
  saveAndLeave: "Enregistrer et quitter",
  unsavedChangesDescription:
    "Vous avez des modifications non enregistrées. Que souhaitez-vous faire avant de quitter cette page ?",
  discardDraftTitle: "Abandonner ?",
  discardDraftDescription:
    "Les informations saisies seront perdues si vous fermez maintenant.",
  discard: "Abandonner",
  clearChatHistoryTitle: "Effacer l'historique du chat",
  clearChatHistoryDesc:
    "Toutes les conversations avec l'assistant seront supprimées. Cette action est irréversible.",
  chooseBaseResume: "Choisissez un CV de base pour commencer",
  configureJobDetails: "Configurez l'offre et la méthode d'adaptation",
  noBaseResumesDesc:
    "Créez d'abord un CV de base avant de créer une version sur mesure.",
  aiSuggestions: "Suggestions IA",
  logout: "Déconnexion",
  signingOut: "Déconnexion…",
  errorSigningOut: "Erreur de déconnexion",
  tryAgain: "Réessayez",
  coverLetterLabel: "Lettre de motivation",
  nameSizeLabel: "Taille du nom",
} as const;
