-- Digimytch Talent Hub — ONE-SHOT init for Supabase.com
-- Paste this ENTIRE file in SQL Editor → Run once
-- Generated by: node scripts/build-cloud-init-sql.mjs

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;


-- ===== schema.sql =====
-- ResumeLM Database Schema
-- This file contains all the SQL statements needed to set up the ResumeLM database schema
-- Run this against your PostgreSQL database to create all required tables

-- First, ensure the UUID extension is available
-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- Subscriptions table
CREATE TABLE IF NOT EXISTS public.subscriptions (
  user_id uuid NOT NULL,
  stripe_customer_id text NULL,
  stripe_subscription_id text NULL,
  subscription_plan text NULL DEFAULT 'free'::text,
  subscription_status text NULL,
  current_period_end timestamp with time zone NULL,
  trial_end timestamp with time zone NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (user_id),
  CONSTRAINT subscriptions_user_id_key UNIQUE (user_id),
  CONSTRAINT subscriptions_stripe_subscription_id_key UNIQUE (stripe_subscription_id),
  CONSTRAINT subscriptions_stripe_customer_id_key UNIQUE (stripe_customer_id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT subscriptions_subscription_plan_check CHECK (
    (
      subscription_plan = ANY (ARRAY['free'::text, 'pro'::text])
    )
  ),
  CONSTRAINT subscriptions_subscription_status_check CHECK (
    (
      (subscription_status IS NULL)
      OR (
        subscription_status = ANY (ARRAY['active'::text, 'canceled'::text])
      )
    )
  )
) TABLESPACE pg_default;

-- Create updated_at trigger for subscriptions
DROP TRIGGER IF EXISTS update_subscriptions_updated_at ON public.subscriptions;
CREATE TRIGGER update_subscriptions_updated_at BEFORE
UPDATE ON subscriptions FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Stripe webhook idempotency table
CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  event_id text NOT NULL,
  event_type text NOT NULL,
  processed_at timestamp with time zone NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stripe_webhook_events_pkey PRIMARY KEY (event_id)
) TABLESPACE pg_default;

DROP TRIGGER IF EXISTS update_stripe_webhook_events_updated_at ON public.stripe_webhook_events;
CREATE TRIGGER update_stripe_webhook_events_updated_at BEFORE
UPDATE ON stripe_webhook_events FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.stripe_webhook_events FROM anon, authenticated;
GRANT ALL ON TABLE public.stripe_webhook_events TO service_role;

-- Jobs table
CREATE TABLE IF NOT EXISTS public.jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  company_name text NULL,
  position_title text NOT NULL,
  job_url text NULL,
  description text NULL,
  location text NULL,
  salary_range text NULL,
  keywords jsonb NULL DEFAULT '[]'::jsonb,
  work_location text NULL DEFAULT 'in_person'::text,
  employment_type text NULL DEFAULT 'full_time'::text,
  is_active boolean NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

-- Create updated_at trigger for jobs
DROP TRIGGER IF EXISTS update_jobs_updated_at ON public.jobs;
CREATE TRIGGER update_jobs_updated_at BEFORE
UPDATE ON jobs FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Resumes table
CREATE TABLE IF NOT EXISTS public.resumes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  job_id uuid NULL,
  is_base_resume boolean NULL DEFAULT false,
  name text NOT NULL,
  first_name text NULL,
  last_name text NULL,
  email text NULL,
  phone_number text NULL,
  location text NULL,
  website text NULL,
  linkedin_url text NULL,
  github_url text NULL,
  professional_summary text NULL,
  work_experience jsonb NULL DEFAULT '[]'::jsonb,
  education jsonb NULL DEFAULT '[]'::jsonb,
  skills jsonb NULL DEFAULT '[]'::jsonb,
  projects jsonb NULL DEFAULT '[]'::jsonb,
  certifications jsonb NULL DEFAULT '[]'::jsonb,
  section_order jsonb NULL DEFAULT '["professional_summary", "work_experience", "skills", "projects", "education", "certifications"]'::jsonb,
  section_configs jsonb NULL DEFAULT '{"skills": {"style": "grouped", "visible": true}, "projects": {"visible": true, "max_items": 3}, "education": {"visible": true, "max_items": null}, "certifications": {"visible": true}, "work_experience": {"visible": true, "max_items": null}}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  resume_title text NULL,
  target_role text NULL,
  document_settings jsonb NULL DEFAULT '{"header_name_size": 24, "skills_margin_top": 2, "document_font_size": 10, "projects_margin_top": 2, "skills_item_spacing": 2, "document_line_height": 1.5, "education_margin_top": 2, "skills_margin_bottom": 2, "experience_margin_top": 2, "projects_item_spacing": 4, "education_item_spacing": 4, "projects_margin_bottom": 2, "education_margin_bottom": 2, "experience_item_spacing": 4, "document_margin_vertical": 36, "experience_margin_bottom": 2, "skills_margin_horizontal": 0, "document_margin_horizontal": 36, "header_name_bottom_spacing": 24, "projects_margin_horizontal": 0, "education_margin_horizontal": 0, "experience_margin_horizontal": 0}'::jsonb,
  has_cover_letter boolean NOT NULL DEFAULT false,
  cover_letter jsonb NULL,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

-- Create updated_at trigger for resumes
DROP TRIGGER IF EXISTS update_resumes_updated_at ON public.resumes;
CREATE TRIGGER update_resumes_updated_at BEFORE
UPDATE ON resumes FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  user_id uuid NOT NULL,
  first_name text NULL,
  last_name text NULL,
  email text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  phone_number text NULL,
  location text NULL,
  website text NULL,
  linkedin_url text NULL,
  github_url text NULL,
  is_admin boolean NOT NULL DEFAULT false,
  work_experience jsonb NULL DEFAULT '[]'::jsonb,
  education jsonb NULL DEFAULT '[]'::jsonb,
  skills jsonb NULL DEFAULT '[]'::jsonb,
  projects jsonb NULL DEFAULT '[]'::jsonb,
  certifications jsonb NULL DEFAULT '[]'::jsonb,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_key UNIQUE (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;

-- Create updated_at trigger for profiles
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE
UPDATE ON profiles FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Setup Row Level Security (RLS) Policies
-- These policies ensure users can only access their own data

-- Subscriptions RLS
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY subscriptions_policy ON public.subscriptions
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- Resumes RLS
ALTER TABLE public.resumes ENABLE ROW LEVEL SECURITY;
CREATE POLICY resumes_policy ON public.resumes
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- Jobs RLS
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY jobs_policy ON public.jobs
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- Profiles RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_policy ON public.profiles
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);


-- ===== 20260215120000_digimytch_courses_applications.sql =====
-- Digimytch Talent Hub: catalogue formations + suivi candidatures (PostgreSQL / Supabase)
-- Réf. cahier des charges DIGI-PFE-2026-02

CREATE TABLE IF NOT EXISTS public.courses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  provider text NOT NULL,
  skills_targeted text[] NOT NULL DEFAULT '{}'::text[],
  level text NOT NULL DEFAULT 'Intermédiaire',
  url text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.job_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  job_id uuid NOT NULL,
  resume_id uuid NULL,
  status text NOT NULL DEFAULT 'saved'::text,
  notes text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_user_job UNIQUE (user_id, job_id),
  CONSTRAINT job_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT job_applications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT job_applications_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT job_applications_status_check CHECK (
    status = ANY (ARRAY['saved'::text, 'applied'::text, 'interview'::text, 'rejected'::text, 'accepted'::text])
  )
);

CREATE TABLE IF NOT EXISTS public.job_application_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  application_id uuid NOT NULL,
  from_status text NULL,
  to_status text NOT NULL,
  note text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT job_application_events_pkey PRIMARY KEY (id),
  CONSTRAINT job_application_events_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.job_applications (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS job_applications_user_id_idx ON public.job_applications USING btree (user_id);
CREATE INDEX IF NOT EXISTS job_applications_job_id_idx ON public.job_applications USING btree (job_id);
CREATE INDEX IF NOT EXISTS job_application_events_application_id_idx ON public.job_application_events USING btree (application_id);

CREATE TRIGGER update_job_applications_updated_at
  BEFORE UPDATE ON public.job_applications
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_application_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY courses_read_authenticated ON public.courses
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY job_applications_select_own ON public.job_applications
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY job_applications_insert_own ON public.job_applications
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY job_applications_update_own ON public.job_applications
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY job_applications_delete_own ON public.job_applications
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY job_application_events_select_own ON public.job_application_events
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.job_applications ja
      WHERE ja.id = job_application_events.application_id AND ja.user_id = auth.uid()
    )
  );

CREATE POLICY job_application_events_insert_own ON public.job_application_events
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.job_applications ja
      WHERE ja.id = job_application_events.application_id AND ja.user_id = auth.uid()
    )
  );

GRANT SELECT ON TABLE public.courses TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.job_applications TO authenticated;
GRANT SELECT, INSERT ON TABLE public.job_application_events TO authenticated;

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Parcours Full-Stack JavaScript', 'Digimytch Academy', ARRAY['react','node.js','typescript','sql'], 'Intermédiaire', 'https://example.org/courses/fullstack-js'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Parcours Full-Stack JavaScript');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Fondamentaux PostgreSQL & SQL', 'OpenClassrooms', ARRAY['sql','postgresql','database'], 'Débutant', 'https://example.org/courses/sql-postgres'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Fondamentaux PostgreSQL & SQL');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Docker & déploiement cloud', 'Digimytch Academy', ARRAY['docker','devops','ci/cd'], 'Intermédiaire', 'https://example.org/courses/docker'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Docker & déploiement cloud');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'API REST & sécurité (Node.js)', 'Digimytch Academy', ARRAY['rest','api','security','nodejs'], 'Avancé', 'https://example.org/courses/rest-security'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'API REST & sécurité (Node.js)');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Introduction à l’IA générative pour développeurs', 'Digimytch Academy', ARRAY['ai','llm','prompt engineering'], 'Débutant', 'https://example.org/courses/genai-dev'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Introduction à l’IA générative pour développeurs');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Scrum & gestion de projet agile', 'Digimytch Academy', ARRAY['scrum','agile','project management'], 'Débutant', 'https://example.org/courses/scrum'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Scrum & gestion de projet agile');


-- ===== 202605030002_create_ai_usage_events.sql =====
CREATE TABLE IF NOT EXISTS public.ai_usage_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  route text NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  is_pro boolean NOT NULL DEFAULT false,
  used_server_key boolean NOT NULL DEFAULT false,
  status text NOT NULL CHECK (status IN ('started', 'succeeded', 'failed', 'rate_limited', 'blocked')),
  error_code text NULL,
  input_tokens integer NULL,
  output_tokens integer NULL,
  total_tokens integer NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT ai_usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ai_usage_events_user_created_idx
ON public.ai_usage_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ai_usage_events_route_created_idx
ON public.ai_usage_events (route, created_at DESC);

ALTER TABLE public.ai_usage_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.ai_usage_events FROM anon, authenticated;
GRANT ALL ON TABLE public.ai_usage_events TO service_role;


-- ===== 20260503022114_create_stripe_webhook_events.sql =====
CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  event_id text NOT NULL,
  event_type text NOT NULL,
  processed_at timestamp with time zone NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stripe_webhook_events_pkey PRIMARY KEY (event_id)
);

DROP TRIGGER IF EXISTS update_stripe_webhook_events_updated_at ON public.stripe_webhook_events;

CREATE TRIGGER update_stripe_webhook_events_updated_at
BEFORE UPDATE ON public.stripe_webhook_events
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ===== 20260503022343_secure_stripe_webhook_events_rls.sql =====
ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.stripe_webhook_events FROM anon, authenticated;
GRANT ALL ON TABLE public.stripe_webhook_events TO service_role;


-- ===== 20260520160000_digimytch_more_courses.sql =====
-- Catalogue élargi : soft skills, carrière, langues, management (pas que hard skills)
-- Colonnes utilisées plus bas (loyalty migration peut arriver après par timestamp)
ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS institution text NULL,
  ADD COLUMN IF NOT EXISTS institution_logo_url text NULL,
  ADD COLUMN IF NOT EXISTS is_digimytch boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS loyalty_points_reward integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duration_hours integer NULL,
  ADD COLUMN IF NOT EXISTS certificate boolean NOT NULL DEFAULT false;

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Communication professionnelle & prise de parole', 'Digimytch Academy', ARRAY['communication','presentation','soft skills'], 'Débutant', 'https://example.org/courses/communication'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Communication professionnelle & prise de parole');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Leadership & travail en équipe', 'Digimytch Academy', ARRAY['leadership','teamwork','management'], 'Intermédiaire', 'https://example.org/courses/leadership'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Leadership & travail en équipe');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Anglais professionnel (B2 → C1)', 'British Council Tunisie', ARRAY['english','communication','soft skills'], 'Intermédiaire', 'https://example.org/courses/english-pro'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Anglais professionnel (B2 → C1)');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Français rédactionnel — CV & entretien', 'Digimytch Academy', ARRAY['french','writing','career'], 'Débutant', 'https://example.org/courses/french-career'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Français rédactionnel — CV & entretien');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Personal branding LinkedIn', 'Digimytch Academy', ARRAY['linkedin','personal branding','networking'], 'Débutant', 'https://example.org/courses/linkedin'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Personal branding LinkedIn');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Gestion du temps & productivité', 'OpenClassrooms', ARRAY['productivity','organization','soft skills'], 'Débutant', 'https://example.org/courses/productivity'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Gestion du temps & productivité');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Négociation salariale (marché tunisien)', 'Digimytch Academy', ARRAY['negotiation','career','soft skills'], 'Intermédiaire', 'https://example.org/courses/negotiation'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Négociation salariale (marché tunisien)');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Design UX/UI — Figma', 'GoMyCode', ARRAY['figma','ux','ui design'], 'Débutant', 'https://example.org/courses/figma-ux'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Design UX/UI — Figma');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Marketing digital & réseaux sociaux', 'Digimytch Academy', ARRAY['marketing','seo','social media'], 'Intermédiaire', 'https://example.org/courses/digital-marketing'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Marketing digital & réseaux sociaux');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Comptabilité & finance pour non-financiers', 'ESAA Tunis', ARRAY['finance','accounting','business'], 'Débutant', 'https://example.org/courses/finance-basics'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Comptabilité & finance pour non-financiers');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Cybersécurité — bonnes pratiques', 'Digimytch Academy', ARRAY['security','cybersecurity','awareness'], 'Débutant', 'https://example.org/courses/cyber-awareness'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Cybersécurité — bonnes pratiques');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Data Analyst — Power BI & Excel', 'Digimytch Academy', ARRAY['power bi','excel','data analysis'], 'Intermédiaire', 'https://example.org/courses/powerbi'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Data Analyst — Power BI & Excel');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Entrepreneuriat & création de startup', 'Flat6Labs', ARRAY['entrepreneurship','startup','business plan'], 'Débutant', 'https://example.org/courses/startup'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Entrepreneuriat & création de startup');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'React.js avancé — hooks & performance', 'Digimytch Academy', ARRAY['react','javascript','frontend'], 'Avancé', 'https://example.org/courses/react-advanced'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'React.js avancé — hooks & performance');

INSERT INTO public.courses (title, provider, skills_targeted, level, url)
SELECT 'Python pour l''automatisation', 'GoMyCode', ARRAY['python','automation','scripting'], 'Intermédiaire', 'https://example.org/courses/python-auto'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Python pour l''automatisation');

-- ── Digimytch Academy exclusive courses (with loyalty points) ────────────────
INSERT INTO public.courses (title, provider, institution, is_digimytch, loyalty_points_reward, skills_targeted, level, url, certificate)
SELECT
  'Préparer son entretien d''embauche avec l''IA',
  'Digimytch Academy',
  'Digimytch Academy',
  true,
  200,
  ARRAY['interview','communication','job search'],
  'Débutant',
  'https://talent.digimytch.tn/courses/interview-prep',
  true
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Préparer son entretien d''embauche avec l''IA');

INSERT INTO public.courses (title, provider, institution, is_digimytch, loyalty_points_reward, skills_targeted, level, url, certificate)
SELECT
  'Optimiser son CV pour les ATS',
  'Digimytch Academy',
  'Digimytch Academy',
  true,
  150,
  ARRAY['cv','ats','job search','resume'],
  'Débutant',
  'https://talent.digimytch.tn/courses/cv-ats',
  true
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Optimiser son CV pour les ATS');

INSERT INTO public.courses (title, provider, institution, is_digimytch, loyalty_points_reward, skills_targeted, level, url, certificate)
SELECT
  'Introduction au marché de l''emploi tunisien',
  'Digimytch Academy',
  'Digimytch Academy',
  true,
  100,
  ARRAY['career','networking','tunisia','job market'],
  'Débutant',
  'https://talent.digimytch.tn/courses/job-market',
  false
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Introduction au marché de l''emploi tunisien');

-- ── Courses with real institutions ───────────────────────────────────────────
INSERT INTO public.courses (title, provider, institution, skills_targeted, level, url)
SELECT 'Google Analytics 4 — Formation officielle', 'Google', 'Google', ARRAY['analytics','marketing','data'], 'Débutant', 'https://skillshop.withgoogle.com/'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Google Analytics 4 — Formation officielle');

INSERT INTO public.courses (title, provider, institution, skills_targeted, level, url)
SELECT 'AWS Cloud Practitioner Essentials', 'Amazon', 'Amazon Web Services', ARRAY['aws','cloud','devops'], 'Débutant', 'https://aws.amazon.com/training/'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'AWS Cloud Practitioner Essentials');

INSERT INTO public.courses (title, provider, institution, skills_targeted, level, url)
SELECT 'Microsoft Azure Fundamentals (AZ-900)', 'Microsoft', 'Microsoft', ARRAY['azure','cloud','microsoft'], 'Débutant', 'https://learn.microsoft.com/en-us/certifications/'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Microsoft Azure Fundamentals (AZ-900)');

INSERT INTO public.courses (title, provider, institution, skills_targeted, level, url)
SELECT 'Machine Learning Specialization', 'Coursera / Stanford', 'Stanford University', ARRAY['machine learning','python','ai','deep learning'], 'Avancé', 'https://www.coursera.org/specializations/machine-learning-introduction'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Machine Learning Specialization');

INSERT INTO public.courses (title, provider, institution, skills_targeted, level, url)
SELECT 'CS50: Introduction to Computer Science', 'edX / Harvard', 'Harvard University', ARRAY['programming','python','c','algorithms'], 'Débutant', 'https://cs50.harvard.edu/'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'CS50: Introduction to Computer Science');

INSERT INTO public.courses (title, provider, institution, skills_targeted, level, url)
SELECT 'Meta Front-End Developer Certificate', 'Coursera / Meta', 'Meta', ARRAY['react','javascript','frontend','css'], 'Intermédiaire', 'https://www.coursera.org/professional-certificates/meta-front-end-developer'
WHERE NOT EXISTS (SELECT 1 FROM public.courses WHERE title = 'Meta Front-End Developer Certificate');


-- ===== 20260523000000_avatars_bucket.sql =====
-- Profil : avatar + nom affiché
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS avatar_url text NULL,
  ADD COLUMN IF NOT EXISTS full_name text NULL;

-- Bucket Storage pour les avatars (public en lecture)
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Users can upload their own avatar" ON storage.objects;
CREATE POLICY "Users can upload their own avatar"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'avatars' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

DROP POLICY IF EXISTS "Avatars are publicly readable" ON storage.objects;
CREATE POLICY "Avatars are publicly readable"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Users can update their own avatar" ON storage.objects;
CREATE POLICY "Users can update their own avatar"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'avatars' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

DROP POLICY IF EXISTS "Users can delete their own avatar" ON storage.objects;
CREATE POLICY "Users can delete their own avatar"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'avatars' AND
  auth.uid()::text = (storage.foldername(name))[1]
);


-- ===== 20260524000000_storage_search_path.sql =====
-- Compatibilité Supabase Storage API (Knex) en Docker local
CREATE SCHEMA IF NOT EXISTS extensions;

ALTER DATABASE postgres SET search_path TO storage, public;


-- ===== 20260524120000_card_images.sql =====
-- Images pour cartes formations et offres (URL publique, ex. Unsplash)

ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS image_url text NULL;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS image_url text NULL;

COMMENT ON COLUMN public.courses.image_url IS 'URL illustration carte formation (16:9 recommandé)';
COMMENT ON COLUMN public.jobs.image_url IS 'URL illustration carte offre (16:10 recommandé)';


-- ===== 20260528143000_rls_auth_uid_select_cache.sql =====
-- Hardened RLS predicates to avoid row-by-row auth.uid() calls.
-- Note: courses has no user_id column and interview_sessions table is absent in this schema.

DROP POLICY IF EXISTS resumes_policy ON public.resumes;
CREATE POLICY resumes_policy ON public.resumes
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS jobs_policy ON public.jobs;
CREATE POLICY jobs_policy ON public.jobs
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS job_applications_select_own ON public.job_applications;
CREATE POLICY job_applications_select_own ON public.job_applications
  FOR SELECT TO authenticated
  USING (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS job_applications_insert_own ON public.job_applications;
CREATE POLICY job_applications_insert_own ON public.job_applications
  FOR INSERT TO authenticated
  WITH CHECK (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS job_applications_update_own ON public.job_applications;
CREATE POLICY job_applications_update_own ON public.job_applications
  FOR UPDATE TO authenticated
  USING (((SELECT auth.uid()) = user_id))
  WITH CHECK (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS job_applications_delete_own ON public.job_applications;
CREATE POLICY job_applications_delete_own ON public.job_applications
  FOR DELETE TO authenticated
  USING (((SELECT auth.uid()) = user_id));


-- ===== 20260528150000_perf_indexes_and_job_cache.sql =====
-- Performance indexes + job analysis cache + atomic status update RPC

CREATE TABLE IF NOT EXISTS public.job_analysis_cache (
  job_hash text PRIMARY KEY,
  analysis jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_resumes_user_id ON public.resumes(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_user_id ON public.jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_user_id_active ON public.jobs(user_id, is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_job_applications_user_id ON public.job_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON public.job_applications(status);
CREATE INDEX IF NOT EXISTS idx_job_application_events_application_id
  ON public.job_application_events(application_id);

CREATE OR REPLACE FUNCTION public.update_application_status(
  app_id uuid,
  new_status text,
  user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prev_status text;
BEGIN
  IF new_status NOT IN ('saved', 'applied', 'interview', 'rejected', 'accepted') THEN
    RAISE EXCEPTION 'Invalid status';
  END IF;

  SELECT status INTO prev_status
  FROM public.job_applications
  WHERE id = app_id AND job_applications.user_id = user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Application not found';
  END IF;

  UPDATE public.job_applications
  SET status = new_status,
      updated_at = timezone('utc'::text, now())
  WHERE id = app_id AND user_id = user_id;

  IF prev_status IS DISTINCT FROM new_status THEN
    INSERT INTO public.job_application_events(application_id, from_status, to_status)
    VALUES (app_id, prev_status, new_status);
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.update_application_status(uuid, text, uuid) TO authenticated;

CREATE INDEX IF NOT EXISTS idx_courses_level ON public.courses(level);

ALTER TABLE public.job_analysis_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY job_analysis_cache_select_authenticated ON public.job_analysis_cache
  FOR SELECT TO authenticated USING (true);

CREATE POLICY job_analysis_cache_upsert_authenticated ON public.job_analysis_cache
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON TABLE public.job_analysis_cache TO authenticated;


-- ===== 20260530000000_admin_role.sql =====
-- Migration: Admin role management
-- Adds a secure server-side function to grant/revoke admin via app_metadata.
-- This cannot be called by regular users (SECURITY DEFINER + explicit caller check).

-- Function to grant admin role (call via service role only)
CREATE OR REPLACE FUNCTION public.set_admin_role(target_user_id uuid, grant_admin boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only allow service role or existing admins to call this
  IF (auth.jwt() ->> 'role') NOT IN ('service_role') THEN
    RAISE EXCEPTION 'Insufficient privileges';
  END IF;

  UPDATE auth.users
  SET raw_app_meta_data =
    CASE
      WHEN grant_admin THEN
        COALESCE(raw_app_meta_data, '{}'::jsonb) || '{"is_admin": true}'::jsonb
      ELSE
        COALESCE(raw_app_meta_data, '{}'::jsonb) - 'is_admin'
    END
  WHERE id = target_user_id;
END;
$$;

-- Seed admin from env if SEED_ADMIN_EMAIL matches an existing user
-- This runs on migration and is idempotent
DO $$
DECLARE
  v_admin_email text := current_setting('app.seed_admin_email', true);
  v_user_id uuid;
BEGIN
  IF v_admin_email IS NULL OR v_admin_email = '' OR v_admin_email = 'admin@admin.com' THEN
    -- Use the known seed email for local Docker setup only
    v_admin_email := 'admin@admin.com';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = lower(v_admin_email) LIMIT 1;

  IF v_user_id IS NOT NULL THEN
    UPDATE auth.users
    SET raw_app_meta_data = COALESCE(raw_app_meta_data, '{}'::jsonb) || '{"is_admin": true}'::jsonb
    WHERE id = v_user_id;
    RAISE NOTICE 'Admin role granted to %', v_admin_email;
  ELSE
    RAISE NOTICE 'Admin user % not found — skipping seed', v_admin_email;
  END IF;
END;
$$;


-- ===== 20260531000000_loyalty_points.sql =====
-- ============================================================
-- Loyalty Points System — Digimytch Talent Hub
-- ============================================================

-- 1. Add institution + is_digimytch columns to courses
ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS institution text NULL,
  ADD COLUMN IF NOT EXISTS institution_logo_url text NULL,
  ADD COLUMN IF NOT EXISTS is_digimytch boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS loyalty_points_reward integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duration_hours integer NULL,
  ADD COLUMN IF NOT EXISTS certificate boolean NOT NULL DEFAULT false;

-- 2. Loyalty points table
CREATE TABLE IF NOT EXISTS public.loyalty_points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  points integer NOT NULL DEFAULT 0,
  total_earned integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT loyalty_points_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_points_user_id_key UNIQUE (user_id),
  CONSTRAINT loyalty_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

-- 3. Course completions (tracks which courses a user completed)
CREATE TABLE IF NOT EXISTS public.course_completions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  completed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  points_earned integer NOT NULL DEFAULT 0,
  CONSTRAINT course_completions_pkey PRIMARY KEY (id),
  CONSTRAINT course_completions_user_course UNIQUE (user_id, course_id),
  CONSTRAINT course_completions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT course_completions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses (id) ON DELETE CASCADE
);

-- 4. RLS policies
ALTER TABLE public.loyalty_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_completions ENABLE ROW LEVEL SECURITY;

CREATE POLICY loyalty_points_own ON public.loyalty_points
  FOR ALL TO authenticated USING (auth.uid() = user_id);

CREATE POLICY course_completions_own ON public.course_completions
  FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 5. Function to add points when a Digimytch course is completed
CREATE OR REPLACE FUNCTION public.complete_digimytch_course(p_course_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_course record;
  v_already_completed boolean;
  v_new_points integer;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT * INTO v_course FROM courses WHERE id = p_course_id AND is_digimytch = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Course not found or not a Digimytch course';
  END IF;

  SELECT EXISTS(
    SELECT 1 FROM course_completions WHERE user_id = v_user_id AND course_id = p_course_id
  ) INTO v_already_completed;

  IF v_already_completed THEN
    RETURN json_build_object('ok', false, 'error', 'Course already completed');
  END IF;

  INSERT INTO course_completions (user_id, course_id, points_earned)
  VALUES (v_user_id, p_course_id, v_course.loyalty_points_reward);

  INSERT INTO loyalty_points (user_id, points, total_earned)
  VALUES (v_user_id, v_course.loyalty_points_reward, v_course.loyalty_points_reward)
  ON CONFLICT (user_id) DO UPDATE
    SET points = loyalty_points.points + v_course.loyalty_points_reward,
        total_earned = loyalty_points.total_earned + v_course.loyalty_points_reward,
        updated_at = now();

  SELECT points INTO v_new_points FROM loyalty_points WHERE user_id = v_user_id;

  RETURN json_build_object(
    'ok', true,
    'points_earned', v_course.loyalty_points_reward,
    'total_points', v_new_points
  );
END;
$$;

-- 6. Update Digimytch courses seed data with institutions + loyalty points
UPDATE public.courses SET
  institution = 'Digimytch Academy',
  institution_logo_url = '/digimytch-logo.png',
  is_digimytch = true,
  loyalty_points_reward = 150,
  certificate = true
WHERE provider = 'Digimytch';

-- 7. Add institutions to known providers
UPDATE public.courses SET institution = 'Google', institution_logo_url = '/logos/google.png'
  WHERE provider ILIKE '%google%';
UPDATE public.courses SET institution = 'Meta', institution_logo_url = '/logos/meta.png'
  WHERE provider ILIKE '%meta%' OR provider ILIKE '%facebook%';
UPDATE public.courses SET institution = 'Microsoft', institution_logo_url = '/logos/microsoft.webp'
  WHERE provider ILIKE '%microsoft%';
UPDATE public.courses SET institution = 'Amazon / AWS', institution_logo_url = '/logos/amazon.png'
  WHERE provider ILIKE '%amazon%' OR provider ILIKE '%aws%';

-- 8. Trigger for updated_at on loyalty_points
CREATE TRIGGER update_loyalty_points_updated_at
  BEFORE UPDATE ON public.loyalty_points
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- ===== 20260531120000_candidate_feedback.sql =====
CREATE TABLE IF NOT EXISTS public.candidate_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_email text,
  category text NOT NULL CHECK (category IN ('rating', 'complaint', 'suggestion')),
  rating smallint CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
  experience_choice text CHECK (
    experience_choice IS NULL OR experience_choice IN ('excellent', 'good', 'average', 'poor')
  ),
  message text,
  page_path text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS candidate_feedback_created_idx
  ON public.candidate_feedback (created_at DESC);

CREATE INDEX IF NOT EXISTS candidate_feedback_user_idx
  ON public.candidate_feedback (user_id, created_at DESC);

ALTER TABLE public.candidate_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY candidate_feedback_insert_own
  ON public.candidate_feedback
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY candidate_feedback_select_own
  ON public.candidate_feedback
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

REVOKE ALL ON TABLE public.candidate_feedback FROM anon;
GRANT SELECT, INSERT ON TABLE public.candidate_feedback TO authenticated;
GRANT ALL ON TABLE public.candidate_feedback TO service_role;


-- ===== 20260531120000_fix_update_application_status_rpc.sql =====
-- Fix ambiguous user_id in update_application_status (parameter vs column)

CREATE OR REPLACE FUNCTION public.update_application_status(
  app_id uuid,
  new_status text,
  user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prev_status text;
  p_user_id uuid := user_id;
BEGIN
  IF new_status NOT IN ('saved', 'applied', 'interview', 'rejected', 'accepted') THEN
    RAISE EXCEPTION 'Invalid status';
  END IF;

  SELECT ja.status INTO prev_status
  FROM public.job_applications ja
  WHERE ja.id = app_id AND ja.user_id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Application not found';
  END IF;

  UPDATE public.job_applications ja
  SET status = new_status,
      updated_at = timezone('utc'::text, now())
  WHERE ja.id = app_id AND ja.user_id = p_user_id;

  IF prev_status IS DISTINCT FROM new_status THEN
    INSERT INTO public.job_application_events(application_id, from_status, to_status)
    VALUES (app_id, prev_status, new_status);
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.update_application_status(uuid, text, uuid) TO authenticated;


-- ===== 20260601120000_soft_delete_and_feedback_reply.sql =====
-- Soft delete (corbeille 30 jours) + réponses admin aux réclamations

ALTER TABLE public.resumes
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE public.job_applications
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_resumes_user_trash
  ON public.resumes (user_id, deleted_at DESC)
  WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_jobs_user_trash
  ON public.jobs (user_id, deleted_at DESC)
  WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_job_applications_user_trash
  ON public.job_applications (user_id, deleted_at DESC)
  WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_courses_trash
  ON public.courses (deleted_at DESC)
  WHERE deleted_at IS NOT NULL;

-- Réponses admin aux réclamations
ALTER TABLE public.candidate_feedback
  ADD COLUMN IF NOT EXISTS admin_reply text,
  ADD COLUMN IF NOT EXISTS admin_reply_at timestamptz,
  ADD COLUMN IF NOT EXISTS admin_replied_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'open';

ALTER TABLE public.candidate_feedback
  DROP CONSTRAINT IF EXISTS candidate_feedback_status_check;

ALTER TABLE public.candidate_feedback
  ADD CONSTRAINT candidate_feedback_status_check
  CHECK (status IN ('open', 'replied', 'closed'));


-- ===== 20260605120000_pgvector_semantic_matching.sql =====
-- Semantic job–resume matching via pgvector (1536-dim, cosine / HNSW)
-- Local Supabase Docker installe le type dans le schéma `storage`

ALTER TABLE public.jobs DROP COLUMN IF EXISTS embedding;
ALTER TABLE public.resumes DROP COLUMN IF EXISTS embedding;

ALTER TABLE public.jobs
  ADD COLUMN embedding vector(1536);

ALTER TABLE public.resumes
  ADD COLUMN embedding vector(1536);

DROP INDEX IF EXISTS idx_jobs_embedding_hnsw;
DROP INDEX IF EXISTS idx_resumes_embedding_hnsw;

CREATE INDEX idx_jobs_embedding_hnsw
  ON public.jobs
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64)
  WHERE embedding IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX idx_resumes_embedding_hnsw
  ON public.resumes
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64)
  WHERE embedding IS NOT NULL AND deleted_at IS NULL;

CREATE OR REPLACE FUNCTION public.match_jobs_semantic(
  p_user_id uuid,
  p_resume_embedding vector(1536),
  p_match_threshold float DEFAULT 0.25,
  p_match_count int DEFAULT 40
)
RETURNS TABLE (
  job_id uuid,
  similarity float
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, extensions
AS $$
  SELECT
    j.id AS job_id,
    (1 - (j.embedding <=> p_resume_embedding))::float AS similarity
  FROM public.jobs j
  WHERE j.user_id = p_user_id
    AND j.is_active = true
    AND j.deleted_at IS NULL
    AND j.embedding IS NOT NULL
    AND (1 - (j.embedding <=> p_resume_embedding)) >= p_match_threshold
  ORDER BY j.embedding <=> p_resume_embedding
  LIMIT GREATEST(p_match_count, 1);
$$;

CREATE OR REPLACE FUNCTION public.job_resume_semantic_similarity(
  p_job_id uuid,
  p_resume_id uuid
)
RETURNS float
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, extensions
AS $$
  SELECT CASE
    WHEN j.embedding IS NULL OR r.embedding IS NULL THEN NULL
    ELSE (1 - (j.embedding <=> r.embedding))::float
  END
  FROM public.jobs j
  INNER JOIN public.resumes r ON r.id = p_resume_id AND r.user_id = j.user_id
  WHERE j.id = p_job_id
    AND j.deleted_at IS NULL
    AND r.deleted_at IS NULL;
$$;

GRANT EXECUTE ON FUNCTION public.match_jobs_semantic(uuid, vector, float, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.job_resume_semantic_similarity(uuid, uuid) TO authenticated;


-- ===== 20260607120000_supabase_linter_performance_fixes.sql =====
-- Supabase database linter: auth RLS initplan, duplicate indexes, overlapping policies.

-- 1. Auth RLS initplan: evaluate auth.uid() once per query, not per row.
DROP POLICY IF EXISTS subscriptions_policy ON public.subscriptions;
CREATE POLICY subscriptions_policy ON public.subscriptions
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS profiles_policy ON public.profiles;
CREATE POLICY profiles_policy ON public.profiles
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS job_application_events_select_own ON public.job_application_events;
CREATE POLICY job_application_events_select_own ON public.job_application_events
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.job_applications ja
      WHERE ja.id = job_application_events.application_id
        AND ja.user_id = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS job_application_events_insert_own ON public.job_application_events;
CREATE POLICY job_application_events_insert_own ON public.job_application_events
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.job_applications ja
      WHERE ja.id = job_application_events.application_id
        AND ja.user_id = (SELECT auth.uid())
    )
  );

DROP POLICY IF EXISTS candidate_feedback_insert_own ON public.candidate_feedback;
CREATE POLICY candidate_feedback_insert_own ON public.candidate_feedback
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS candidate_feedback_select_own ON public.candidate_feedback;
CREATE POLICY candidate_feedback_select_own ON public.candidate_feedback
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS loyalty_points_own ON public.loyalty_points;
CREATE POLICY loyalty_points_own ON public.loyalty_points
  FOR ALL TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS course_completions_own ON public.course_completions;
CREATE POLICY course_completions_own ON public.course_completions
  FOR ALL TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- 2. Multiple permissive SELECT policies on job_analysis_cache (FOR ALL already covers SELECT).
DROP POLICY IF EXISTS job_analysis_cache_select_authenticated ON public.job_analysis_cache;

-- 3. Duplicate indexes (keep idx_* names from perf migration).
DROP INDEX IF EXISTS public.job_application_events_application_id_idx;
DROP INDEX IF EXISTS public.job_applications_user_id_idx;


-- ===== 20260607130000_supabase_linter_remaining_fixes.sql =====
-- Supabase database linter: remaining security/performance fixes.

-- 1. Function search_path (SECURITY: function_search_path_mutable).
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- 2. Unindexed foreign keys on public tables (PERFORMANCE: unindexed_foreign_keys).
CREATE INDEX IF NOT EXISTS idx_candidate_feedback_admin_replied_by
  ON public.candidate_feedback (admin_replied_by);

CREATE INDEX IF NOT EXISTS idx_course_completions_course_id
  ON public.course_completions (course_id);

CREATE INDEX IF NOT EXISTS idx_job_applications_resume_id
  ON public.job_applications (resume_id);

CREATE INDEX IF NOT EXISTS idx_resumes_job_id
  ON public.resumes (job_id);

-- 3. RLS enabled without policies on service-role-only tables (SECURITY: rls_enabled_no_policy).
-- Client roles are revoked; explicit deny documents intent and satisfies the linter.
CREATE POLICY ai_usage_events_deny_clients ON public.ai_usage_events
  FOR ALL TO authenticated, anon
  USING (false)
  WITH CHECK (false);

CREATE POLICY stripe_webhook_events_deny_clients ON public.stripe_webhook_events
  FOR ALL TO authenticated, anon
  USING (false)
  WITH CHECK (false);


-- ===== 20260607140000_fix_update_application_status_auth.sql =====
-- Bind SECURITY DEFINER RPC to the authenticated caller (prevents user_id spoofing).

CREATE OR REPLACE FUNCTION public.update_application_status(
  app_id uuid,
  new_status text,
  user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prev_status text;
  p_user_id uuid := auth.uid();
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF user_id IS DISTINCT FROM p_user_id THEN
    RAISE EXCEPTION 'Forbidden';
  END IF;

  IF new_status NOT IN ('saved', 'applied', 'interview', 'rejected', 'accepted') THEN
    RAISE EXCEPTION 'Invalid status';
  END IF;

  SELECT ja.status INTO prev_status
  FROM public.job_applications ja
  WHERE ja.id = app_id AND ja.user_id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Application not found';
  END IF;

  UPDATE public.job_applications ja
  SET status = new_status,
      updated_at = timezone('utc'::text, now())
  WHERE ja.id = app_id AND ja.user_id = p_user_id;

  IF prev_status IS DISTINCT FROM new_status THEN
    INSERT INTO public.job_application_events(application_id, from_status, to_status)
    VALUES (app_id, prev_status, new_status);
  END IF;
END;
$$;


-- ===== 20260607150000_rls_soft_delete_insert_hardening.sql =====
-- Require deleted_at IS NULL on INSERT; keep SELECT/UPDATE/DELETE for trash restore/purge.

DROP POLICY IF EXISTS resumes_policy ON public.resumes;
CREATE POLICY resumes_select_own ON public.resumes
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY resumes_insert_own ON public.resumes
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id AND deleted_at IS NULL);
CREATE POLICY resumes_update_own ON public.resumes
  FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY resumes_delete_own ON public.resumes
  FOR DELETE TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS jobs_policy ON public.jobs;
CREATE POLICY jobs_select_own ON public.jobs
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY jobs_insert_own ON public.jobs
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id AND deleted_at IS NULL);
CREATE POLICY jobs_update_own ON public.jobs
  FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY jobs_delete_own ON public.jobs
  FOR DELETE TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS job_applications_insert_own ON public.job_applications;
CREATE POLICY job_applications_insert_own ON public.job_applications
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id AND deleted_at IS NULL);


-- ===== 20260609120000_refresh_card_images.sql =====
-- Refresh course & job card images with curated Unsplash URLs (verified 2026-06).
-- Safe to re-run: only updates rows matched by title/company.

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Parcours Full-Stack JavaScript';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Fondamentaux PostgreSQL & SQL';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Docker & déploiement cloud';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'API REST & sécurité (Node.js)';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title IN (
  'Introduction à l''IA générative pour développeurs',
  'Introduction à l’IA générative pour développeurs'
);

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Scrum & gestion de projet agile';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Communication professionnelle & prise de parole';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Leadership & travail en équipe';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Anglais professionnel (B2 → C1)';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Français rédactionnel — CV & entretien';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title IN (
  'Personal branding LinkedIn',
  'Introduction au marché de l''emploi tunisien',
  'Introduction au marché de l’emploi tunisien'
);

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Gestion du temps & productivité';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Négociation salariale (marché tunisien)';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Design UX/UI — Figma';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Marketing digital & réseaux sociaux';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Comptabilité & finance pour non-financiers';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Cybersécurité — bonnes pratiques';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Data Analyst — Power BI & Excel';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Entrepreneuriat & création de startup';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'React.js avancé — hooks & performance';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title IN ('Python pour l''automatisation', 'Python pour l’automatisation');

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title IN (
  'Préparer son entretien d''embauche avec l''IA',
  'Préparer son entretien d’embauche avec l’IA'
);

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Optimiser son CV pour les ATS';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Google Analytics 4 — Formation officielle';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'AWS Cloud Practitioner Essentials';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'Microsoft Azure Fundamentals (AZ-900)';

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title IN (
  'Machine Learning Specialization',
  'Meta Front-End Developer Certificate'
);

UPDATE public.courses SET image_url = 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&h=450&q=80'
WHERE title = 'CS50: Introduction to Computer Science';

-- Platform catalogue jobs (match by company + title)
UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Vermeg' AND position_title = 'Développeur Full Stack Java / React';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Focus Corporation' AND position_title = 'Ingénieur DevOps';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Expensya' AND position_title = 'Développeur Frontend React';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Orange Tunisie' AND position_title = 'Chef de projet digital';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'InstaDeep' AND position_title = 'Machine Learning Engineer';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Talabat (Delivery Hero)' AND position_title = 'Backend Developer Node.js';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'BIAT' AND position_title = 'Analyste données junior';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Digimytch' AND position_title = 'Stagiaire PFE — Talent Hub';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Société Générale' AND position_title = 'Développeur Java confirmé';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Beekeeper' AND position_title = 'Développeur mobile Flutter';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Proxym Group' AND position_title = 'Ingénieur QA / Test automation';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Wally' AND position_title = 'Data Engineer';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Stark Industries' AND position_title = 'Product Owner junior';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Cloudflare (partenaire)' AND position_title = 'Site Reliability Engineer';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'Ooredoo Tunisie' AND position_title = 'Consultant CRM Salesforce';

UPDATE public.jobs SET image_url = 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&h=450&q=80'
WHERE company_name = 'DEPT®' AND position_title = 'UX/UI Designer';

